# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T13:04:13+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field, RootModel, SecretStr, conint, constr


class AccessDeniedException(RootModel[Any]):
    root: Any


class Arn(
    RootModel[
        constr(
            pattern=r'^arn:(aws|aws-cn|aws-us-gov):[a-zA-Z0-9-]+:[a-zA-Z0-9-]*:\d{12}:([\w+=,.@-]+[/:])*[\w+=,.@-]+$',
            min_length=1,
            max_length=200,
        )
    ]
):
    root: constr(
        pattern=r'^arn:(aws|aws-cn|aws-us-gov):[a-zA-Z0-9-]+:[a-zA-Z0-9-]*:\d{12}:([\w+=,.@-]+[/:])*[\w+=,.@-]+$',
        min_length=1,
        max_length=200,
    )


class AwsAccountId(RootModel[constr(pattern=r'^\d{12}$')]):
    root: constr(pattern=r'^\d{12}$')


class BlockerStatus(Enum):
    ACTIVE = 'ACTIVE'
    RESOLVED = 'RESOLVED'


class BlockerType(Enum):
    AUTOMATED = 'AUTOMATED'


class Boolean(RootModel[bool]):
    root: bool


class ClientToken(RootModel[constr(pattern=r'^[!-~]*$', min_length=0, max_length=64)]):
    root: constr(pattern=r'^[!-~]*$', min_length=0, max_length=64)


class ComponentArn(RootModel[str]):
    root: str


class ComponentDeploymentUpdateType(Enum):
    NONE = 'NONE'
    CURRENT_VERSION = 'CURRENT_VERSION'


class ConflictException(RootModel[Any]):
    root: Any


class DeploymentId(
    RootModel[
        constr(
            pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        )
    ]
):
    root: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )


class DeploymentStatus(Enum):
    IN_PROGRESS = 'IN_PROGRESS'
    FAILED = 'FAILED'
    SUCCEEDED = 'SUCCEEDED'
    DELETE_IN_PROGRESS = 'DELETE_IN_PROGRESS'
    DELETE_FAILED = 'DELETE_FAILED'
    DELETE_COMPLETE = 'DELETE_COMPLETE'
    CANCELLING = 'CANCELLING'
    CANCELLED = 'CANCELLED'


class DeploymentUpdateType(Enum):
    NONE = 'NONE'
    CURRENT_VERSION = 'CURRENT_VERSION'
    MINOR_VERSION = 'MINOR_VERSION'
    MAJOR_VERSION = 'MAJOR_VERSION'


class Description(RootModel[SecretStr]):
    root: SecretStr


class DisplayName(RootModel[SecretStr]):
    root: SecretStr


class EmptyNextToken(RootModel[constr(min_length=0, max_length=0)]):
    root: constr(min_length=0, max_length=0)


class EnvironmentAccountConnectionArn(RootModel[str]):
    root: str


class EnvironmentAccountConnectionId(
    RootModel[
        constr(
            pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        )
    ]
):
    root: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )


class EnvironmentAccountConnectionRequesterAccountType(Enum):
    MANAGEMENT_ACCOUNT = 'MANAGEMENT_ACCOUNT'
    ENVIRONMENT_ACCOUNT = 'ENVIRONMENT_ACCOUNT'


class EnvironmentAccountConnectionStatus(Enum):
    PENDING = 'PENDING'
    CONNECTED = 'CONNECTED'
    REJECTED = 'REJECTED'


class EnvironmentAccountConnectionStatusList(
    RootModel[List[EnvironmentAccountConnectionStatus]]
):
    root: List[EnvironmentAccountConnectionStatus]


class EnvironmentArn(RootModel[str]):
    root: str


class EnvironmentTemplateArn(RootModel[str]):
    root: str


class EnvironmentTemplateVersionArn(RootModel[str]):
    root: str


class FullTemplateVersionNumber(
    RootModel[
        constr(
            pattern=r'^(0|([1-9]{1}\d*)).(0|([1-9]{1}\d*))$',
            min_length=1,
            max_length=10,
        )
    ]
):
    root: constr(
        pattern=r'^(0|([1-9]{1}\d*)).(0|([1-9]{1}\d*))$', min_length=1, max_length=10
    )


class GetAccountSettingsInput(BaseModel):
    pass


class GetEnvironmentAccountConnectionInput(BaseModel):
    id: EnvironmentAccountConnectionId


class GetResourcesSummaryInput(BaseModel):
    pass


class GitBranchName(RootModel[constr(min_length=1, max_length=200)]):
    root: constr(min_length=1, max_length=200)


class Integer(RootModel[int]):
    root: int


class InternalServerException(RootModel[Any]):
    root: Any


class ListServiceInstancesFilterBy(Enum):
    name = 'name'
    deploymentStatus = 'deploymentStatus'
    templateName = 'templateName'
    serviceName = 'serviceName'
    deployedTemplateVersionStatus = 'deployedTemplateVersionStatus'
    environmentName = 'environmentName'
    lastDeploymentAttemptedAtBefore = 'lastDeploymentAttemptedAtBefore'
    lastDeploymentAttemptedAtAfter = 'lastDeploymentAttemptedAtAfter'
    createdAtBefore = 'createdAtBefore'
    createdAtAfter = 'createdAtAfter'


class ListServiceInstancesFilterValue(RootModel[str]):
    root: str


class ListServiceInstancesSortBy(Enum):
    name = 'name'
    deploymentStatus = 'deploymentStatus'
    templateName = 'templateName'
    serviceName = 'serviceName'
    environmentName = 'environmentName'
    lastDeploymentAttemptedAt = 'lastDeploymentAttemptedAt'
    createdAt = 'createdAt'


class MaxPageResults(RootModel[conint(ge=1, le=100)]):
    root: conint(ge=1, le=100)


class NextToken(RootModel[constr(pattern=r'^[A-Za-z0-9+=/]+$')]):
    root: constr(pattern=r'^[A-Za-z0-9+=/]+$')


class NotifyResourceDeploymentStatusChangeInputStatusMessageString(
    RootModel[SecretStr]
):
    root: SecretStr


class NotifyResourceDeploymentStatusChangeOutput(BaseModel):
    pass


class OpsFilePath(RootModel[constr(min_length=1, max_length=4096)]):
    root: constr(min_length=1, max_length=4096)


class OutputKey(RootModel[constr(min_length=1, max_length=1024)]):
    root: constr(min_length=1, max_length=1024)


class OutputValueString(RootModel[constr(min_length=1, max_length=1024)]):
    root: constr(min_length=1, max_length=1024)


class ProvisionedResourceEngine(Enum):
    CLOUDFORMATION = 'CLOUDFORMATION'
    TERRAFORM = 'TERRAFORM'


class ProvisionedResourceIdentifier(RootModel[constr(min_length=1, max_length=200)]):
    root: constr(min_length=1, max_length=200)


class ProvisionedResourceName(RootModel[constr(min_length=1, max_length=200)]):
    root: constr(min_length=1, max_length=200)


class Provisioning(Enum):
    CUSTOMER_MANAGED = 'CUSTOMER_MANAGED'


class RejectEnvironmentAccountConnectionInput(BaseModel):
    id: EnvironmentAccountConnectionId


class RepositoryArn(RootModel[str]):
    root: str


class RepositoryId(RootModel[constr(min_length=1, max_length=200)]):
    root: constr(min_length=1, max_length=200)


class RepositoryName(
    RootModel[
        constr(
            pattern=r'[A-Za-z0-9_.-].*/[A-Za-z0-9_.-].*', min_length=1, max_length=100
        )
    ]
):
    root: constr(
        pattern=r'[A-Za-z0-9_.-].*/[A-Za-z0-9_.-].*', min_length=1, max_length=100
    )


class RepositoryProvider(Enum):
    GITHUB = 'GITHUB'
    GITHUB_ENTERPRISE = 'GITHUB_ENTERPRISE'
    BITBUCKET = 'BITBUCKET'


class RepositorySummary(BaseModel):
    arn: RepositoryArn
    connectionArn: Arn
    name: RepositoryName
    provider: RepositoryProvider


class RepositorySummaryList(RootModel[List[RepositorySummary]]):
    root: List[RepositorySummary]


class RepositorySyncStatus(Enum):
    INITIATED = 'INITIATED'
    IN_PROGRESS = 'IN_PROGRESS'
    SUCCEEDED = 'SUCCEEDED'
    FAILED = 'FAILED'
    QUEUED = 'QUEUED'


class ResourceCountsSummary(BaseModel):
    behindMajor: Optional[Integer] = None
    behindMinor: Optional[Integer] = None
    failed: Optional[Integer] = None
    total: Integer
    upToDate: Optional[Integer] = None


class ResourceDeploymentStatus(Enum):
    IN_PROGRESS = 'IN_PROGRESS'
    FAILED = 'FAILED'
    SUCCEEDED = 'SUCCEEDED'


class ResourceName(
    RootModel[
        constr(pattern=r'^[0-9A-Za-z]+[0-9A-Za-z_\-]*$', min_length=1, max_length=100)
    ]
):
    root: constr(pattern=r'^[0-9A-Za-z]+[0-9A-Za-z_\-]*$', min_length=1, max_length=100)


class ResourceNameOrEmpty(
    RootModel[
        constr(
            pattern=r'(^$)|^[0-9A-Za-z]+[0-9A-Za-z_\-]*$', min_length=0, max_length=100
        )
    ]
):
    root: constr(
        pattern=r'(^$)|^[0-9A-Za-z]+[0-9A-Za-z_\-]*$', min_length=0, max_length=100
    )


class ResourceNotFoundException(RootModel[Any]):
    root: Any


class ResourceSyncStatus(Enum):
    INITIATED = 'INITIATED'
    IN_PROGRESS = 'IN_PROGRESS'
    SUCCEEDED = 'SUCCEEDED'
    FAILED = 'FAILED'


class RoleArn(
    RootModel[
        constr(
            pattern=r'^arn:(aws|aws-cn|aws-us-gov):iam::\d{12}:role/([\w+=,.@-]{1,512}[/:])*([\w+=,.@-]{1,64})$',
            min_length=1,
            max_length=2048,
        )
    ]
):
    root: constr(
        pattern=r'^arn:(aws|aws-cn|aws-us-gov):iam::\d{12}:role/([\w+=,.@-]{1,512}[/:])*([\w+=,.@-]{1,64})$',
        min_length=1,
        max_length=2048,
    )


class RoleArnOrEmptyString(
    RootModel[
        constr(
            pattern=r'(^$)|(^arn:(aws|aws-cn|aws-us-gov):iam::\d{12}:role/([\w+=,.@-]{1,512}[/:])*([\w+=,.@-]{1,64})$)',
            min_length=0,
            max_length=2048,
        )
    ]
):
    root: constr(
        pattern=r'(^$)|(^arn:(aws|aws-cn|aws-us-gov):iam::\d{12}:role/([\w+=,.@-]{1,512}[/:])*([\w+=,.@-]{1,64})$)',
        min_length=0,
        max_length=2048,
    )


class S3Bucket(
    RootModel[
        constr(pattern=r'^[a-z0-9]+[a-z0-9-\.]+[a-z0-9]+$', min_length=3, max_length=63)
    ]
):
    root: constr(
        pattern=r'^[a-z0-9]+[a-z0-9-\.]+[a-z0-9]+$', min_length=3, max_length=63
    )


class S3Key(RootModel[constr(min_length=1, max_length=1024)]):
    root: constr(min_length=1, max_length=1024)


class S3ObjectSource(BaseModel):
    bucket: S3Bucket
    key: S3Key


class SHA(RootModel[constr(min_length=1, max_length=255)]):
    root: constr(min_length=1, max_length=255)


class ServiceArn(RootModel[str]):
    root: str


class ServiceInstanceArn(RootModel[str]):
    root: str


class ServiceQuotaExceededException(RootModel[Any]):
    root: Any


class ServiceStatus(Enum):
    CREATE_IN_PROGRESS = 'CREATE_IN_PROGRESS'
    CREATE_FAILED_CLEANUP_IN_PROGRESS = 'CREATE_FAILED_CLEANUP_IN_PROGRESS'
    CREATE_FAILED_CLEANUP_COMPLETE = 'CREATE_FAILED_CLEANUP_COMPLETE'
    CREATE_FAILED_CLEANUP_FAILED = 'CREATE_FAILED_CLEANUP_FAILED'
    CREATE_FAILED = 'CREATE_FAILED'
    ACTIVE = 'ACTIVE'
    DELETE_IN_PROGRESS = 'DELETE_IN_PROGRESS'
    DELETE_FAILED = 'DELETE_FAILED'
    UPDATE_IN_PROGRESS = 'UPDATE_IN_PROGRESS'
    UPDATE_FAILED_CLEANUP_IN_PROGRESS = 'UPDATE_FAILED_CLEANUP_IN_PROGRESS'
    UPDATE_FAILED_CLEANUP_COMPLETE = 'UPDATE_FAILED_CLEANUP_COMPLETE'
    UPDATE_FAILED_CLEANUP_FAILED = 'UPDATE_FAILED_CLEANUP_FAILED'
    UPDATE_FAILED = 'UPDATE_FAILED'
    UPDATE_COMPLETE_CLEANUP_FAILED = 'UPDATE_COMPLETE_CLEANUP_FAILED'


class ServiceSyncConfig(BaseModel):
    branch: GitBranchName
    filePath: OpsFilePath
    repositoryName: RepositoryName
    repositoryProvider: RepositoryProvider
    serviceName: ResourceName


class ServiceTemplateArn(RootModel[str]):
    root: str


class ServiceTemplateSupportedComponentSourceType(Enum):
    DIRECTLY_DEFINED = 'DIRECTLY_DEFINED'


class ServiceTemplateVersionArn(RootModel[str]):
    root: str


class SortOrder(Enum):
    ASCENDING = 'ASCENDING'
    DESCENDING = 'DESCENDING'


class SpecContents(RootModel[SecretStr]):
    root: SecretStr


class StatusMessage(RootModel[SecretStr]):
    root: SecretStr


class String(RootModel[str]):
    root: str


class Subdirectory(RootModel[constr(min_length=1, max_length=4096)]):
    root: constr(min_length=1, max_length=4096)


class SyncBlockerContext(BaseModel):
    key: String
    value: String


class SyncBlockerContexts(RootModel[List[SyncBlockerContext]]):
    root: List[SyncBlockerContext]


class SyncType(Enum):
    TEMPLATE_SYNC = 'TEMPLATE_SYNC'
    SERVICE_SYNC = 'SERVICE_SYNC'


class TagKey(RootModel[constr(min_length=1, max_length=128)]):
    root: constr(min_length=1, max_length=128)


class TagKeyList(RootModel[List[TagKey]]):
    root: List[TagKey] = Field(..., max_length=50, min_length=0)


class TagResourceOutput(BaseModel):
    pass


class TagValue(RootModel[constr(min_length=0, max_length=256)]):
    root: constr(min_length=0, max_length=256)


class TemplateFileContents(RootModel[SecretStr]):
    root: SecretStr


class TemplateManifestContents(RootModel[SecretStr]):
    root: SecretStr


class TemplateSchema(RootModel[SecretStr]):
    root: SecretStr


class TemplateType(Enum):
    ENVIRONMENT = 'ENVIRONMENT'
    SERVICE = 'SERVICE'


class TemplateVersionPart(
    RootModel[constr(pattern=r'^(0|([1-9]{1}\d*))$', min_length=1, max_length=20)]
):
    root: constr(pattern=r'^(0|([1-9]{1}\d*))$', min_length=1, max_length=20)


class TemplateVersionSourceInput(BaseModel):
    s3: Optional[S3ObjectSource] = None


class TemplateVersionStatus(Enum):
    REGISTRATION_IN_PROGRESS = 'REGISTRATION_IN_PROGRESS'
    REGISTRATION_FAILED = 'REGISTRATION_FAILED'
    DRAFT = 'DRAFT'
    PUBLISHED = 'PUBLISHED'


class ThrottlingException(RootModel[Any]):
    root: Any


class Timestamp(RootModel[datetime]):
    root: datetime


class UntagResourceInput(BaseModel):
    resourceArn: Arn
    tagKeys: TagKeyList


class UntagResourceOutput(BaseModel):
    pass


class UpdateComponentInput(BaseModel):
    clientToken: Optional[ClientToken] = None
    deploymentType: ComponentDeploymentUpdateType
    description: Optional[Description] = None
    name: ResourceName
    serviceInstanceName: Optional[ResourceNameOrEmpty] = None
    serviceName: Optional[ResourceNameOrEmpty] = None
    serviceSpec: Optional[SpecContents] = None
    templateFile: Optional[TemplateFileContents] = None


class UpdateEnvironmentAccountConnectionInput(BaseModel):
    codebuildRoleArn: Optional[RoleArn] = None
    componentRoleArn: Optional[RoleArn] = None
    id: EnvironmentAccountConnectionId
    roleArn: Optional[RoleArn] = None


class UpdateEnvironmentTemplateInput(BaseModel):
    description: Optional[Description] = None
    displayName: Optional[DisplayName] = None
    name: ResourceName


class UpdateEnvironmentTemplateVersionInput(BaseModel):
    description: Optional[Description] = None
    majorVersion: TemplateVersionPart
    minorVersion: TemplateVersionPart
    status: Optional[TemplateVersionStatus] = None
    templateName: ResourceName


class UpdateServiceInput(BaseModel):
    description: Optional[Description] = None
    name: ResourceName
    spec: Optional[SpecContents] = None


class UpdateServiceInstanceInput(BaseModel):
    clientToken: Optional[ClientToken] = None
    deploymentType: DeploymentUpdateType
    name: ResourceName
    serviceName: ResourceName
    spec: Optional[SpecContents] = None
    templateMajorVersion: Optional[TemplateVersionPart] = None
    templateMinorVersion: Optional[TemplateVersionPart] = None


class UpdateServicePipelineInput(BaseModel):
    deploymentType: DeploymentUpdateType
    serviceName: ResourceName
    spec: SpecContents
    templateMajorVersion: Optional[TemplateVersionPart] = None
    templateMinorVersion: Optional[TemplateVersionPart] = None


class UpdateServiceSyncBlockerInput(BaseModel):
    id: String
    resolvedReason: String


class UpdateServiceSyncConfigInput(BaseModel):
    branch: GitBranchName
    filePath: OpsFilePath
    repositoryName: RepositoryName
    repositoryProvider: RepositoryProvider
    serviceName: ResourceName


class UpdateServiceSyncConfigOutput(BaseModel):
    serviceSyncConfig: Optional[ServiceSyncConfig] = None


class UpdateServiceTemplateInput(BaseModel):
    description: Optional[Description] = None
    displayName: Optional[DisplayName] = None
    name: ResourceName


class UpdateTemplateSyncConfigInput(BaseModel):
    branch: GitBranchName
    repositoryName: RepositoryName
    repositoryProvider: RepositoryProvider
    subdirectory: Optional[Subdirectory] = None
    templateName: ResourceName
    templateType: TemplateType


class ValidationException(RootModel[Any]):
    root: Any


class XAmzTarget(Enum):
    AwsProton20200720_AcceptEnvironmentAccountConnection = (
        'AwsProton20200720.AcceptEnvironmentAccountConnection'
    )


class XAmzTarget1(Enum):
    AwsProton20200720_CancelComponentDeployment = (
        'AwsProton20200720.CancelComponentDeployment'
    )


class XAmzTarget2(Enum):
    AwsProton20200720_CancelEnvironmentDeployment = (
        'AwsProton20200720.CancelEnvironmentDeployment'
    )


class XAmzTarget3(Enum):
    AwsProton20200720_CancelServiceInstanceDeployment = (
        'AwsProton20200720.CancelServiceInstanceDeployment'
    )


class XAmzTarget4(Enum):
    AwsProton20200720_CancelServicePipelineDeployment = (
        'AwsProton20200720.CancelServicePipelineDeployment'
    )


class XAmzTarget5(Enum):
    AwsProton20200720_CreateComponent = 'AwsProton20200720.CreateComponent'


class XAmzTarget6(Enum):
    AwsProton20200720_CreateEnvironment = 'AwsProton20200720.CreateEnvironment'


class XAmzTarget7(Enum):
    AwsProton20200720_CreateEnvironmentAccountConnection = (
        'AwsProton20200720.CreateEnvironmentAccountConnection'
    )


class XAmzTarget8(Enum):
    AwsProton20200720_CreateEnvironmentTemplate = (
        'AwsProton20200720.CreateEnvironmentTemplate'
    )


class XAmzTarget9(Enum):
    AwsProton20200720_CreateEnvironmentTemplateVersion = (
        'AwsProton20200720.CreateEnvironmentTemplateVersion'
    )


class XAmzTarget10(Enum):
    AwsProton20200720_CreateRepository = 'AwsProton20200720.CreateRepository'


class XAmzTarget11(Enum):
    AwsProton20200720_CreateService = 'AwsProton20200720.CreateService'


class XAmzTarget12(Enum):
    AwsProton20200720_CreateServiceInstance = 'AwsProton20200720.CreateServiceInstance'


class XAmzTarget13(Enum):
    AwsProton20200720_CreateServiceSyncConfig = (
        'AwsProton20200720.CreateServiceSyncConfig'
    )


class XAmzTarget14(Enum):
    AwsProton20200720_CreateServiceTemplate = 'AwsProton20200720.CreateServiceTemplate'


class XAmzTarget15(Enum):
    AwsProton20200720_CreateServiceTemplateVersion = (
        'AwsProton20200720.CreateServiceTemplateVersion'
    )


class XAmzTarget16(Enum):
    AwsProton20200720_CreateTemplateSyncConfig = (
        'AwsProton20200720.CreateTemplateSyncConfig'
    )


class XAmzTarget17(Enum):
    AwsProton20200720_DeleteComponent = 'AwsProton20200720.DeleteComponent'


class XAmzTarget18(Enum):
    AwsProton20200720_DeleteEnvironment = 'AwsProton20200720.DeleteEnvironment'


class XAmzTarget19(Enum):
    AwsProton20200720_DeleteEnvironmentAccountConnection = (
        'AwsProton20200720.DeleteEnvironmentAccountConnection'
    )


class XAmzTarget20(Enum):
    AwsProton20200720_DeleteEnvironmentTemplate = (
        'AwsProton20200720.DeleteEnvironmentTemplate'
    )


class XAmzTarget21(Enum):
    AwsProton20200720_DeleteEnvironmentTemplateVersion = (
        'AwsProton20200720.DeleteEnvironmentTemplateVersion'
    )


class XAmzTarget22(Enum):
    AwsProton20200720_DeleteRepository = 'AwsProton20200720.DeleteRepository'


class XAmzTarget23(Enum):
    AwsProton20200720_DeleteService = 'AwsProton20200720.DeleteService'


class XAmzTarget24(Enum):
    AwsProton20200720_DeleteServiceSyncConfig = (
        'AwsProton20200720.DeleteServiceSyncConfig'
    )


class XAmzTarget25(Enum):
    AwsProton20200720_DeleteServiceTemplate = 'AwsProton20200720.DeleteServiceTemplate'


class XAmzTarget26(Enum):
    AwsProton20200720_DeleteServiceTemplateVersion = (
        'AwsProton20200720.DeleteServiceTemplateVersion'
    )


class XAmzTarget27(Enum):
    AwsProton20200720_DeleteTemplateSyncConfig = (
        'AwsProton20200720.DeleteTemplateSyncConfig'
    )


class XAmzTarget28(Enum):
    AwsProton20200720_GetAccountSettings = 'AwsProton20200720.GetAccountSettings'


class XAmzTarget29(Enum):
    AwsProton20200720_GetComponent = 'AwsProton20200720.GetComponent'


class XAmzTarget30(Enum):
    AwsProton20200720_GetEnvironment = 'AwsProton20200720.GetEnvironment'


class XAmzTarget31(Enum):
    AwsProton20200720_GetEnvironmentAccountConnection = (
        'AwsProton20200720.GetEnvironmentAccountConnection'
    )


class XAmzTarget32(Enum):
    AwsProton20200720_GetEnvironmentTemplate = (
        'AwsProton20200720.GetEnvironmentTemplate'
    )


class XAmzTarget33(Enum):
    AwsProton20200720_GetEnvironmentTemplateVersion = (
        'AwsProton20200720.GetEnvironmentTemplateVersion'
    )


class XAmzTarget34(Enum):
    AwsProton20200720_GetRepository = 'AwsProton20200720.GetRepository'


class XAmzTarget35(Enum):
    AwsProton20200720_GetRepositorySyncStatus = (
        'AwsProton20200720.GetRepositorySyncStatus'
    )


class XAmzTarget36(Enum):
    AwsProton20200720_GetResourcesSummary = 'AwsProton20200720.GetResourcesSummary'


class XAmzTarget37(Enum):
    AwsProton20200720_GetService = 'AwsProton20200720.GetService'


class XAmzTarget38(Enum):
    AwsProton20200720_GetServiceInstance = 'AwsProton20200720.GetServiceInstance'


class XAmzTarget39(Enum):
    AwsProton20200720_GetServiceInstanceSyncStatus = (
        'AwsProton20200720.GetServiceInstanceSyncStatus'
    )


class XAmzTarget40(Enum):
    AwsProton20200720_GetServiceSyncBlockerSummary = (
        'AwsProton20200720.GetServiceSyncBlockerSummary'
    )


class XAmzTarget41(Enum):
    AwsProton20200720_GetServiceSyncConfig = 'AwsProton20200720.GetServiceSyncConfig'


class XAmzTarget42(Enum):
    AwsProton20200720_GetServiceTemplate = 'AwsProton20200720.GetServiceTemplate'


class XAmzTarget43(Enum):
    AwsProton20200720_GetServiceTemplateVersion = (
        'AwsProton20200720.GetServiceTemplateVersion'
    )


class XAmzTarget44(Enum):
    AwsProton20200720_GetTemplateSyncConfig = 'AwsProton20200720.GetTemplateSyncConfig'


class XAmzTarget45(Enum):
    AwsProton20200720_GetTemplateSyncStatus = 'AwsProton20200720.GetTemplateSyncStatus'


class XAmzTarget46(Enum):
    AwsProton20200720_ListComponentOutputs = 'AwsProton20200720.ListComponentOutputs'


class XAmzTarget47(Enum):
    AwsProton20200720_ListComponentProvisionedResources = (
        'AwsProton20200720.ListComponentProvisionedResources'
    )


class XAmzTarget48(Enum):
    AwsProton20200720_ListComponents = 'AwsProton20200720.ListComponents'


class XAmzTarget49(Enum):
    AwsProton20200720_ListEnvironmentAccountConnections = (
        'AwsProton20200720.ListEnvironmentAccountConnections'
    )


class XAmzTarget50(Enum):
    AwsProton20200720_ListEnvironmentOutputs = (
        'AwsProton20200720.ListEnvironmentOutputs'
    )


class XAmzTarget51(Enum):
    AwsProton20200720_ListEnvironmentProvisionedResources = (
        'AwsProton20200720.ListEnvironmentProvisionedResources'
    )


class XAmzTarget52(Enum):
    AwsProton20200720_ListEnvironmentTemplateVersions = (
        'AwsProton20200720.ListEnvironmentTemplateVersions'
    )


class XAmzTarget53(Enum):
    AwsProton20200720_ListEnvironmentTemplates = (
        'AwsProton20200720.ListEnvironmentTemplates'
    )


class XAmzTarget54(Enum):
    AwsProton20200720_ListEnvironments = 'AwsProton20200720.ListEnvironments'


class XAmzTarget55(Enum):
    AwsProton20200720_ListRepositories = 'AwsProton20200720.ListRepositories'


class XAmzTarget56(Enum):
    AwsProton20200720_ListRepositorySyncDefinitions = (
        'AwsProton20200720.ListRepositorySyncDefinitions'
    )


class XAmzTarget57(Enum):
    AwsProton20200720_ListServiceInstanceOutputs = (
        'AwsProton20200720.ListServiceInstanceOutputs'
    )


class XAmzTarget58(Enum):
    AwsProton20200720_ListServiceInstanceProvisionedResources = (
        'AwsProton20200720.ListServiceInstanceProvisionedResources'
    )


class XAmzTarget59(Enum):
    AwsProton20200720_ListServiceInstances = 'AwsProton20200720.ListServiceInstances'


class XAmzTarget60(Enum):
    AwsProton20200720_ListServicePipelineOutputs = (
        'AwsProton20200720.ListServicePipelineOutputs'
    )


class XAmzTarget61(Enum):
    AwsProton20200720_ListServicePipelineProvisionedResources = (
        'AwsProton20200720.ListServicePipelineProvisionedResources'
    )


class XAmzTarget62(Enum):
    AwsProton20200720_ListServiceTemplateVersions = (
        'AwsProton20200720.ListServiceTemplateVersions'
    )


class XAmzTarget63(Enum):
    AwsProton20200720_ListServiceTemplates = 'AwsProton20200720.ListServiceTemplates'


class XAmzTarget64(Enum):
    AwsProton20200720_ListServices = 'AwsProton20200720.ListServices'


class XAmzTarget65(Enum):
    AwsProton20200720_ListTagsForResource = 'AwsProton20200720.ListTagsForResource'


class XAmzTarget66(Enum):
    AwsProton20200720_NotifyResourceDeploymentStatusChange = (
        'AwsProton20200720.NotifyResourceDeploymentStatusChange'
    )


class XAmzTarget67(Enum):
    AwsProton20200720_RejectEnvironmentAccountConnection = (
        'AwsProton20200720.RejectEnvironmentAccountConnection'
    )


class XAmzTarget68(Enum):
    AwsProton20200720_TagResource = 'AwsProton20200720.TagResource'


class XAmzTarget69(Enum):
    AwsProton20200720_UntagResource = 'AwsProton20200720.UntagResource'


class XAmzTarget70(Enum):
    AwsProton20200720_UpdateAccountSettings = 'AwsProton20200720.UpdateAccountSettings'


class XAmzTarget71(Enum):
    AwsProton20200720_UpdateComponent = 'AwsProton20200720.UpdateComponent'


class XAmzTarget72(Enum):
    AwsProton20200720_UpdateEnvironment = 'AwsProton20200720.UpdateEnvironment'


class XAmzTarget73(Enum):
    AwsProton20200720_UpdateEnvironmentAccountConnection = (
        'AwsProton20200720.UpdateEnvironmentAccountConnection'
    )


class XAmzTarget74(Enum):
    AwsProton20200720_UpdateEnvironmentTemplate = (
        'AwsProton20200720.UpdateEnvironmentTemplate'
    )


class XAmzTarget75(Enum):
    AwsProton20200720_UpdateEnvironmentTemplateVersion = (
        'AwsProton20200720.UpdateEnvironmentTemplateVersion'
    )


class XAmzTarget76(Enum):
    AwsProton20200720_UpdateService = 'AwsProton20200720.UpdateService'


class XAmzTarget77(Enum):
    AwsProton20200720_UpdateServiceInstance = 'AwsProton20200720.UpdateServiceInstance'


class XAmzTarget78(Enum):
    AwsProton20200720_UpdateServicePipeline = 'AwsProton20200720.UpdateServicePipeline'


class XAmzTarget79(Enum):
    AwsProton20200720_UpdateServiceSyncBlocker = (
        'AwsProton20200720.UpdateServiceSyncBlocker'
    )


class XAmzTarget80(Enum):
    AwsProton20200720_UpdateServiceSyncConfig = (
        'AwsProton20200720.UpdateServiceSyncConfig'
    )


class XAmzTarget81(Enum):
    AwsProton20200720_UpdateServiceTemplate = 'AwsProton20200720.UpdateServiceTemplate'


class XAmzTarget82(Enum):
    AwsProton20200720_UpdateServiceTemplateVersion = (
        'AwsProton20200720.UpdateServiceTemplateVersion'
    )


class XAmzTarget83(Enum):
    AwsProton20200720_UpdateTemplateSyncConfig = (
        'AwsProton20200720.UpdateTemplateSyncConfig'
    )


class AcceptEnvironmentAccountConnectionInput(BaseModel):
    id: EnvironmentAccountConnectionId


class CancelComponentDeploymentInput(BaseModel):
    componentName: ResourceName


class CancelEnvironmentDeploymentInput(BaseModel):
    environmentName: ResourceName


class CancelServiceInstanceDeploymentInput(BaseModel):
    serviceInstanceName: ResourceName
    serviceName: ResourceName


class CancelServicePipelineDeploymentInput(BaseModel):
    serviceName: ResourceName


class CompatibleEnvironmentTemplate(BaseModel):
    majorVersion: TemplateVersionPart
    templateName: ResourceName


class CompatibleEnvironmentTemplateInput(BaseModel):
    majorVersion: TemplateVersionPart
    templateName: ResourceName


class CompatibleEnvironmentTemplateInputList(
    RootModel[List[CompatibleEnvironmentTemplateInput]]
):
    root: List[CompatibleEnvironmentTemplateInput] = Field(
        ..., max_length=10, min_length=1
    )


class CompatibleEnvironmentTemplateList(RootModel[List[CompatibleEnvironmentTemplate]]):
    root: List[CompatibleEnvironmentTemplate]


class Component(BaseModel):
    arn: ComponentArn
    createdAt: Timestamp
    deploymentStatus: DeploymentStatus
    deploymentStatusMessage: Optional[StatusMessage] = None
    description: Optional[Description] = None
    environmentName: ResourceName
    lastClientRequestToken: Optional[String] = None
    lastDeploymentAttemptedAt: Optional[Timestamp] = None
    lastDeploymentSucceededAt: Optional[Timestamp] = None
    lastModifiedAt: Timestamp
    name: ResourceName
    serviceInstanceName: Optional[ResourceName] = None
    serviceName: Optional[ResourceName] = None
    serviceSpec: Optional[SpecContents] = None


class ComponentSummary(BaseModel):
    arn: ComponentArn
    createdAt: Timestamp
    deploymentStatus: DeploymentStatus
    deploymentStatusMessage: Optional[StatusMessage] = None
    environmentName: ResourceName
    lastDeploymentAttemptedAt: Optional[Timestamp] = None
    lastDeploymentSucceededAt: Optional[Timestamp] = None
    lastModifiedAt: Timestamp
    name: ResourceName
    serviceInstanceName: Optional[ResourceName] = None
    serviceName: Optional[ResourceName] = None


class ComponentSummaryList(RootModel[List[ComponentSummary]]):
    root: List[ComponentSummary]


class CountsSummary(BaseModel):
    components: Optional[ResourceCountsSummary] = None
    environmentTemplates: Optional[ResourceCountsSummary] = None
    environments: Optional[ResourceCountsSummary] = None
    pipelines: Optional[ResourceCountsSummary] = None
    serviceInstances: Optional[ResourceCountsSummary] = None
    serviceTemplates: Optional[ResourceCountsSummary] = None
    services: Optional[ResourceCountsSummary] = None


class CreateComponentOutput(BaseModel):
    component: Component


class CreateServiceSyncConfigInput(BaseModel):
    branch: GitBranchName
    filePath: OpsFilePath
    repositoryName: RepositoryName
    repositoryProvider: RepositoryProvider
    serviceName: ResourceName


class CreateServiceSyncConfigOutput(BaseModel):
    serviceSyncConfig: Optional[ServiceSyncConfig] = None


class CreateTemplateSyncConfigInput(BaseModel):
    branch: GitBranchName
    repositoryName: RepositoryName
    repositoryProvider: RepositoryProvider
    subdirectory: Optional[Subdirectory] = None
    templateName: ResourceName
    templateType: TemplateType


class DeleteComponentInput(BaseModel):
    name: ResourceName


class DeleteComponentOutput(BaseModel):
    component: Optional[Component] = None


class DeleteEnvironmentAccountConnectionInput(BaseModel):
    id: EnvironmentAccountConnectionId


class DeleteEnvironmentInput(BaseModel):
    name: ResourceName


class DeleteEnvironmentTemplateInput(BaseModel):
    name: ResourceName


class DeleteEnvironmentTemplateVersionInput(BaseModel):
    majorVersion: TemplateVersionPart
    minorVersion: TemplateVersionPart
    templateName: ResourceName


class DeleteRepositoryInput(BaseModel):
    name: RepositoryName
    provider: RepositoryProvider


class DeleteServiceInput(BaseModel):
    name: ResourceName


class DeleteServiceSyncConfigInput(BaseModel):
    serviceName: ResourceName


class DeleteServiceSyncConfigOutput(BaseModel):
    serviceSyncConfig: Optional[ServiceSyncConfig] = None


class DeleteServiceTemplateInput(BaseModel):
    name: ResourceName


class DeleteServiceTemplateVersionInput(BaseModel):
    majorVersion: TemplateVersionPart
    minorVersion: TemplateVersionPart
    templateName: ResourceName


class DeleteTemplateSyncConfigInput(BaseModel):
    templateName: ResourceName
    templateType: TemplateType


class EnvironmentAccountConnection(BaseModel):
    arn: EnvironmentAccountConnectionArn
    codebuildRoleArn: Optional[RoleArn] = None
    componentRoleArn: Optional[RoleArn] = None
    environmentAccountId: AwsAccountId
    environmentName: ResourceName
    id: EnvironmentAccountConnectionId
    lastModifiedAt: Timestamp
    managementAccountId: AwsAccountId
    requestedAt: Timestamp
    roleArn: Arn
    status: EnvironmentAccountConnectionStatus


class EnvironmentAccountConnectionSummary(BaseModel):
    arn: EnvironmentAccountConnectionArn
    componentRoleArn: Optional[Arn] = None
    environmentAccountId: AwsAccountId
    environmentName: ResourceName
    id: EnvironmentAccountConnectionId
    lastModifiedAt: Timestamp
    managementAccountId: AwsAccountId
    requestedAt: Timestamp
    roleArn: Arn
    status: EnvironmentAccountConnectionStatus


class EnvironmentAccountConnectionSummaryList(
    RootModel[List[EnvironmentAccountConnectionSummary]]
):
    root: List[EnvironmentAccountConnectionSummary]


class EnvironmentSummary(BaseModel):
    arn: EnvironmentArn
    componentRoleArn: Optional[Arn] = None
    createdAt: Timestamp
    deploymentStatus: DeploymentStatus
    deploymentStatusMessage: Optional[StatusMessage] = None
    description: Optional[Description] = None
    environmentAccountConnectionId: Optional[EnvironmentAccountConnectionId] = None
    environmentAccountId: Optional[AwsAccountId] = None
    lastDeploymentAttemptedAt: Timestamp
    lastDeploymentSucceededAt: Timestamp
    name: ResourceName
    protonServiceRoleArn: Optional[Arn] = None
    provisioning: Optional[Provisioning] = None
    templateMajorVersion: TemplateVersionPart
    templateMinorVersion: TemplateVersionPart
    templateName: ResourceName


class EnvironmentSummaryList(RootModel[List[EnvironmentSummary]]):
    root: List[EnvironmentSummary]


class EnvironmentTemplate(BaseModel):
    arn: EnvironmentTemplateArn
    createdAt: Timestamp
    description: Optional[Description] = None
    displayName: Optional[DisplayName] = None
    encryptionKey: Optional[Arn] = None
    lastModifiedAt: Timestamp
    name: ResourceName
    provisioning: Optional[Provisioning] = None
    recommendedVersion: Optional[FullTemplateVersionNumber] = None


class EnvironmentTemplateFilter(BaseModel):
    majorVersion: TemplateVersionPart
    templateName: ResourceName


class EnvironmentTemplateFilterList(RootModel[List[EnvironmentTemplateFilter]]):
    root: List[EnvironmentTemplateFilter]


class EnvironmentTemplateSummary(BaseModel):
    arn: EnvironmentTemplateArn
    createdAt: Timestamp
    description: Optional[Description] = None
    displayName: Optional[DisplayName] = None
    lastModifiedAt: Timestamp
    name: ResourceName
    provisioning: Optional[Provisioning] = None
    recommendedVersion: Optional[FullTemplateVersionNumber] = None


class EnvironmentTemplateSummaryList(RootModel[List[EnvironmentTemplateSummary]]):
    root: List[EnvironmentTemplateSummary]


class EnvironmentTemplateVersion(BaseModel):
    arn: EnvironmentTemplateVersionArn
    createdAt: Timestamp
    description: Optional[Description] = None
    lastModifiedAt: Timestamp
    majorVersion: TemplateVersionPart
    minorVersion: TemplateVersionPart
    recommendedMinorVersion: Optional[TemplateVersionPart] = None
    schema_: Optional[TemplateSchema] = Field(None, alias='schema')
    status: TemplateVersionStatus
    statusMessage: Optional[StatusMessage] = None
    templateName: ResourceName


class EnvironmentTemplateVersionSummary(BaseModel):
    arn: EnvironmentTemplateVersionArn
    createdAt: Timestamp
    description: Optional[Description] = None
    lastModifiedAt: Timestamp
    majorVersion: TemplateVersionPart
    minorVersion: TemplateVersionPart
    recommendedMinorVersion: Optional[TemplateVersionPart] = None
    status: TemplateVersionStatus
    statusMessage: Optional[StatusMessage] = None
    templateName: ResourceName


class EnvironmentTemplateVersionSummaryList(
    RootModel[List[EnvironmentTemplateVersionSummary]]
):
    root: List[EnvironmentTemplateVersionSummary]


class GetComponentInput(BaseModel):
    name: ResourceName


class GetComponentOutput(BaseModel):
    component: Optional[Component] = None


class GetEnvironmentAccountConnectionOutput(BaseModel):
    environmentAccountConnection: EnvironmentAccountConnection


class GetEnvironmentInput(BaseModel):
    name: ResourceName


class GetEnvironmentTemplateInput(BaseModel):
    name: ResourceName


class GetEnvironmentTemplateOutput(BaseModel):
    environmentTemplate: EnvironmentTemplate


class GetEnvironmentTemplateVersionInput(BaseModel):
    majorVersion: TemplateVersionPart
    minorVersion: TemplateVersionPart
    templateName: ResourceName


class GetEnvironmentTemplateVersionOutput(BaseModel):
    environmentTemplateVersion: EnvironmentTemplateVersion


class GetRepositoryInput(BaseModel):
    name: RepositoryName
    provider: RepositoryProvider


class GetRepositorySyncStatusInput(BaseModel):
    branch: GitBranchName
    repositoryName: RepositoryName
    repositoryProvider: RepositoryProvider
    syncType: SyncType


class GetResourcesSummaryOutput(BaseModel):
    counts: CountsSummary


class GetServiceInput(BaseModel):
    name: ResourceName


class GetServiceInstanceInput(BaseModel):
    name: ResourceName
    serviceName: ResourceName


class GetServiceInstanceSyncStatusInput(BaseModel):
    serviceInstanceName: ResourceName
    serviceName: ResourceName


class GetServiceSyncBlockerSummaryInput(BaseModel):
    serviceInstanceName: Optional[ResourceName] = None
    serviceName: ResourceName


class GetServiceSyncConfigInput(BaseModel):
    serviceName: ResourceName


class GetServiceSyncConfigOutput(BaseModel):
    serviceSyncConfig: Optional[ServiceSyncConfig] = None


class GetServiceTemplateInput(BaseModel):
    name: ResourceName


class GetServiceTemplateVersionInput(BaseModel):
    majorVersion: TemplateVersionPart
    minorVersion: TemplateVersionPart
    templateName: ResourceName


class GetTemplateSyncConfigInput(BaseModel):
    templateName: ResourceName
    templateType: TemplateType


class GetTemplateSyncStatusInput(BaseModel):
    templateName: ResourceName
    templateType: TemplateType
    templateVersion: TemplateVersionPart


class ListComponentOutputsInput(BaseModel):
    componentName: ResourceName
    nextToken: Optional[EmptyNextToken] = None


class ListComponentProvisionedResourcesInput(BaseModel):
    componentName: ResourceName
    nextToken: Optional[EmptyNextToken] = None


class ListComponentsInput(BaseModel):
    environmentName: Optional[ResourceName] = None
    maxResults: Optional[MaxPageResults] = None
    nextToken: Optional[NextToken] = None
    serviceInstanceName: Optional[ResourceName] = None
    serviceName: Optional[ResourceName] = None


class ListComponentsOutput(BaseModel):
    components: ComponentSummaryList
    nextToken: Optional[NextToken] = None


class ListEnvironmentAccountConnectionsInput(BaseModel):
    environmentName: Optional[ResourceName] = None
    maxResults: Optional[MaxPageResults] = None
    nextToken: Optional[NextToken] = None
    requestedBy: EnvironmentAccountConnectionRequesterAccountType
    statuses: Optional[EnvironmentAccountConnectionStatusList] = None


class ListEnvironmentAccountConnectionsOutput(BaseModel):
    environmentAccountConnections: EnvironmentAccountConnectionSummaryList
    nextToken: Optional[NextToken] = None


class ListEnvironmentOutputsInput(BaseModel):
    environmentName: ResourceName
    nextToken: Optional[EmptyNextToken] = None


class ListEnvironmentProvisionedResourcesInput(BaseModel):
    environmentName: ResourceName
    nextToken: Optional[EmptyNextToken] = None


class ListEnvironmentTemplateVersionsInput(BaseModel):
    majorVersion: Optional[TemplateVersionPart] = None
    maxResults: Optional[MaxPageResults] = None
    nextToken: Optional[NextToken] = None
    templateName: ResourceName


class ListEnvironmentTemplateVersionsOutput(BaseModel):
    nextToken: Optional[NextToken] = None
    templateVersions: EnvironmentTemplateVersionSummaryList


class ListEnvironmentTemplatesInput(BaseModel):
    maxResults: Optional[MaxPageResults] = None
    nextToken: Optional[NextToken] = None


class ListEnvironmentTemplatesOutput(BaseModel):
    nextToken: Optional[NextToken] = None
    templates: EnvironmentTemplateSummaryList


class ListEnvironmentsInput(BaseModel):
    environmentTemplates: Optional[EnvironmentTemplateFilterList] = None
    maxResults: Optional[MaxPageResults] = None
    nextToken: Optional[NextToken] = None


class ListEnvironmentsOutput(BaseModel):
    environments: EnvironmentSummaryList
    nextToken: Optional[NextToken] = None


class ListRepositoriesInput(BaseModel):
    maxResults: Optional[MaxPageResults] = None
    nextToken: Optional[NextToken] = None


class ListRepositoriesOutput(BaseModel):
    nextToken: Optional[NextToken] = None
    repositories: RepositorySummaryList


class ListRepositorySyncDefinitionsInput(BaseModel):
    nextToken: Optional[EmptyNextToken] = None
    repositoryName: RepositoryName
    repositoryProvider: RepositoryProvider
    syncType: SyncType


class ListServiceInstanceOutputsInput(BaseModel):
    nextToken: Optional[EmptyNextToken] = None
    serviceInstanceName: ResourceName
    serviceName: ResourceName


class ListServiceInstanceProvisionedResourcesInput(BaseModel):
    nextToken: Optional[EmptyNextToken] = None
    serviceInstanceName: ResourceName
    serviceName: ResourceName


class ListServiceInstancesFilter(BaseModel):
    key: Optional[ListServiceInstancesFilterBy] = None
    value: Optional[ListServiceInstancesFilterValue] = None


class ListServiceInstancesFilterList(RootModel[List[ListServiceInstancesFilter]]):
    root: List[ListServiceInstancesFilter]


class ListServiceInstancesInput(BaseModel):
    filters: Optional[ListServiceInstancesFilterList] = None
    maxResults: Optional[MaxPageResults] = None
    nextToken: Optional[NextToken] = None
    serviceName: Optional[ResourceName] = None
    sortBy: Optional[ListServiceInstancesSortBy] = None
    sortOrder: Optional[SortOrder] = None


class ListServicePipelineOutputsInput(BaseModel):
    nextToken: Optional[EmptyNextToken] = None
    serviceName: ResourceName


class ListServicePipelineProvisionedResourcesInput(BaseModel):
    nextToken: Optional[EmptyNextToken] = None
    serviceName: ResourceName


class ListServiceTemplateVersionsInput(BaseModel):
    majorVersion: Optional[TemplateVersionPart] = None
    maxResults: Optional[MaxPageResults] = None
    nextToken: Optional[NextToken] = None
    templateName: ResourceName


class ListServiceTemplatesInput(BaseModel):
    maxResults: Optional[MaxPageResults] = None
    nextToken: Optional[NextToken] = None


class ListServicesInput(BaseModel):
    maxResults: Optional[MaxPageResults] = None
    nextToken: Optional[NextToken] = None


class ListTagsForResourceInput(BaseModel):
    maxResults: Optional[MaxPageResults] = None
    nextToken: Optional[String] = None
    resourceArn: Arn


class Output(BaseModel):
    key: Optional[OutputKey] = None
    valueString: Optional[OutputValueString] = None


class OutputsList(RootModel[List[Output]]):
    root: List[Output]


class ProvisionedResource(BaseModel):
    identifier: Optional[ProvisionedResourceIdentifier] = None
    name: Optional[ProvisionedResourceName] = None
    provisioningEngine: Optional[ProvisionedResourceEngine] = None


class ProvisionedResourceList(RootModel[List[ProvisionedResource]]):
    root: List[ProvisionedResource]


class RejectEnvironmentAccountConnectionOutput(BaseModel):
    environmentAccountConnection: EnvironmentAccountConnection


class Repository(BaseModel):
    arn: RepositoryArn
    connectionArn: Arn
    encryptionKey: Optional[Arn] = None
    name: RepositoryName
    provider: RepositoryProvider


class RepositoryBranch(BaseModel):
    arn: RepositoryArn
    branch: GitBranchName
    name: RepositoryName
    provider: RepositoryProvider


class RepositoryBranchInput(BaseModel):
    branch: GitBranchName
    name: RepositoryName
    provider: RepositoryProvider


class RepositorySyncDefinition(BaseModel):
    branch: GitBranchName
    directory: String
    parent: String
    target: String


class RepositorySyncDefinitionList(RootModel[List[RepositorySyncDefinition]]):
    root: List[RepositorySyncDefinition]


class RepositorySyncEvent(BaseModel):
    event: String
    externalId: Optional[String] = None
    time: Timestamp
    type: String


class RepositorySyncEvents(RootModel[List[RepositorySyncEvent]]):
    root: List[RepositorySyncEvent]


class ResourceSyncEvent(BaseModel):
    event: String
    externalId: Optional[String] = None
    time: Timestamp
    type: String


class ResourceSyncEvents(RootModel[List[ResourceSyncEvent]]):
    root: List[ResourceSyncEvent]


class Revision(BaseModel):
    branch: GitBranchName
    directory: String
    repositoryName: RepositoryName
    repositoryProvider: RepositoryProvider
    sha: SHA


class ServiceInstance(BaseModel):
    arn: ServiceInstanceArn
    createdAt: Timestamp
    deploymentStatus: DeploymentStatus
    deploymentStatusMessage: Optional[StatusMessage] = None
    environmentName: ResourceName
    lastClientRequestToken: Optional[String] = None
    lastDeploymentAttemptedAt: Timestamp
    lastDeploymentSucceededAt: Timestamp
    name: ResourceName
    serviceName: ResourceName
    spec: Optional[SpecContents] = None
    templateMajorVersion: TemplateVersionPart
    templateMinorVersion: TemplateVersionPart
    templateName: ResourceName


class ServiceInstanceSummary(BaseModel):
    arn: ServiceInstanceArn
    createdAt: Timestamp
    deploymentStatus: DeploymentStatus
    deploymentStatusMessage: Optional[StatusMessage] = None
    environmentName: ResourceName
    lastDeploymentAttemptedAt: Timestamp
    lastDeploymentSucceededAt: Timestamp
    name: ResourceName
    serviceName: ResourceName
    templateMajorVersion: TemplateVersionPart
    templateMinorVersion: TemplateVersionPart
    templateName: ResourceName


class ServiceInstanceSummaryList(RootModel[List[ServiceInstanceSummary]]):
    root: List[ServiceInstanceSummary]


class ServicePipeline(BaseModel):
    arn: Arn
    createdAt: Timestamp
    deploymentStatus: DeploymentStatus
    deploymentStatusMessage: Optional[StatusMessage] = None
    lastDeploymentAttemptedAt: Timestamp
    lastDeploymentSucceededAt: Timestamp
    spec: Optional[SpecContents] = None
    templateMajorVersion: TemplateVersionPart
    templateMinorVersion: TemplateVersionPart
    templateName: ResourceName


class ServiceSummary(BaseModel):
    arn: ServiceArn
    createdAt: Timestamp
    description: Optional[Description] = None
    lastModifiedAt: Timestamp
    name: ResourceName
    status: ServiceStatus
    statusMessage: Optional[StatusMessage] = None
    templateName: ResourceName


class ServiceSummaryList(RootModel[List[ServiceSummary]]):
    root: List[ServiceSummary]


class ServiceTemplate(BaseModel):
    arn: ServiceTemplateArn
    createdAt: Timestamp
    description: Optional[Description] = None
    displayName: Optional[DisplayName] = None
    encryptionKey: Optional[Arn] = None
    lastModifiedAt: Timestamp
    name: ResourceName
    pipelineProvisioning: Optional[Provisioning] = None
    recommendedVersion: Optional[FullTemplateVersionNumber] = None


class ServiceTemplateSummary(BaseModel):
    arn: ServiceTemplateArn
    createdAt: Timestamp
    description: Optional[Description] = None
    displayName: Optional[DisplayName] = None
    lastModifiedAt: Timestamp
    name: ResourceName
    pipelineProvisioning: Optional[Provisioning] = None
    recommendedVersion: Optional[FullTemplateVersionNumber] = None


class ServiceTemplateSummaryList(RootModel[List[ServiceTemplateSummary]]):
    root: List[ServiceTemplateSummary]


class ServiceTemplateSupportedComponentSourceInputList(
    RootModel[List[ServiceTemplateSupportedComponentSourceType]]
):
    root: List[ServiceTemplateSupportedComponentSourceType]


class ServiceTemplateVersion(BaseModel):
    arn: ServiceTemplateVersionArn
    compatibleEnvironmentTemplates: CompatibleEnvironmentTemplateList
    createdAt: Timestamp
    description: Optional[Description] = None
    lastModifiedAt: Timestamp
    majorVersion: TemplateVersionPart
    minorVersion: TemplateVersionPart
    recommendedMinorVersion: Optional[TemplateVersionPart] = None
    schema_: Optional[TemplateSchema] = Field(None, alias='schema')
    status: TemplateVersionStatus
    statusMessage: Optional[StatusMessage] = None
    supportedComponentSources: Optional[
        ServiceTemplateSupportedComponentSourceInputList
    ] = None
    templateName: ResourceName


class ServiceTemplateVersionSummary(BaseModel):
    arn: ServiceTemplateVersionArn
    createdAt: Timestamp
    description: Optional[Description] = None
    lastModifiedAt: Timestamp
    majorVersion: TemplateVersionPart
    minorVersion: TemplateVersionPart
    recommendedMinorVersion: Optional[TemplateVersionPart] = None
    status: TemplateVersionStatus
    statusMessage: Optional[StatusMessage] = None
    templateName: ResourceName


class ServiceTemplateVersionSummaryList(RootModel[List[ServiceTemplateVersionSummary]]):
    root: List[ServiceTemplateVersionSummary]


class SyncBlocker(BaseModel):
    contexts: Optional[SyncBlockerContexts] = None
    createdAt: Timestamp
    createdReason: String
    id: String
    resolvedAt: Optional[Timestamp] = None
    resolvedReason: Optional[String] = None
    status: BlockerStatus
    type: BlockerType


class Tag(BaseModel):
    key: TagKey
    value: TagValue


class TagList(RootModel[List[Tag]]):
    root: List[Tag] = Field(..., max_length=50, min_length=0)


class TagResourceInput(BaseModel):
    resourceArn: Arn
    tags: TagList


class TemplateSyncConfig(BaseModel):
    branch: GitBranchName
    repositoryName: RepositoryName
    repositoryProvider: RepositoryProvider
    subdirectory: Optional[Subdirectory] = None
    templateName: ResourceName
    templateType: TemplateType


class UpdateAccountSettingsInput(BaseModel):
    deletePipelineProvisioningRepository: Optional[Boolean] = None
    pipelineCodebuildRoleArn: Optional[RoleArnOrEmptyString] = None
    pipelineProvisioningRepository: Optional[RepositoryBranchInput] = None
    pipelineServiceRoleArn: Optional[RoleArnOrEmptyString] = None


class UpdateComponentOutput(BaseModel):
    component: Component


class UpdateEnvironmentAccountConnectionOutput(BaseModel):
    environmentAccountConnection: EnvironmentAccountConnection


class UpdateEnvironmentInput(BaseModel):
    codebuildRoleArn: Optional[RoleArn] = None
    componentRoleArn: Optional[RoleArn] = None
    deploymentType: DeploymentUpdateType
    description: Optional[Description] = None
    environmentAccountConnectionId: Optional[EnvironmentAccountConnectionId] = None
    name: ResourceName
    protonServiceRoleArn: Optional[Arn] = None
    provisioningRepository: Optional[RepositoryBranchInput] = None
    spec: Optional[SpecContents] = None
    templateMajorVersion: Optional[TemplateVersionPart] = None
    templateMinorVersion: Optional[TemplateVersionPart] = None


class UpdateEnvironmentTemplateOutput(BaseModel):
    environmentTemplate: EnvironmentTemplate


class UpdateEnvironmentTemplateVersionOutput(BaseModel):
    environmentTemplateVersion: EnvironmentTemplateVersion


class UpdateServiceInstanceOutput(BaseModel):
    serviceInstance: ServiceInstance


class UpdateServicePipelineOutput(BaseModel):
    pipeline: ServicePipeline


class UpdateServiceSyncBlockerOutput(BaseModel):
    serviceInstanceName: Optional[ResourceName] = None
    serviceName: ResourceName
    serviceSyncBlocker: SyncBlocker


class UpdateServiceTemplateOutput(BaseModel):
    serviceTemplate: ServiceTemplate


class UpdateServiceTemplateVersionInput(BaseModel):
    compatibleEnvironmentTemplates: Optional[CompatibleEnvironmentTemplateInputList] = (
        None
    )
    description: Optional[Description] = None
    majorVersion: TemplateVersionPart
    minorVersion: TemplateVersionPart
    status: Optional[TemplateVersionStatus] = None
    supportedComponentSources: Optional[
        ServiceTemplateSupportedComponentSourceInputList
    ] = None
    templateName: ResourceName


class UpdateServiceTemplateVersionOutput(BaseModel):
    serviceTemplateVersion: ServiceTemplateVersion


class UpdateTemplateSyncConfigOutput(BaseModel):
    templateSyncConfig: Optional[TemplateSyncConfig] = None


class AcceptEnvironmentAccountConnectionOutput(BaseModel):
    environmentAccountConnection: EnvironmentAccountConnection


class AccountSettings(BaseModel):
    pipelineCodebuildRoleArn: Optional[RoleArnOrEmptyString] = None
    pipelineProvisioningRepository: Optional[RepositoryBranch] = None
    pipelineServiceRoleArn: Optional[RoleArnOrEmptyString] = None


class CancelComponentDeploymentOutput(BaseModel):
    component: Component


class CancelServiceInstanceDeploymentOutput(BaseModel):
    serviceInstance: ServiceInstance


class CancelServicePipelineDeploymentOutput(BaseModel):
    pipeline: ServicePipeline


class CreateComponentInput(BaseModel):
    clientToken: Optional[ClientToken] = None
    description: Optional[Description] = None
    environmentName: Optional[ResourceName] = None
    manifest: TemplateManifestContents
    name: ResourceName
    serviceInstanceName: Optional[ResourceName] = None
    serviceName: Optional[ResourceName] = None
    serviceSpec: Optional[SpecContents] = None
    tags: Optional[TagList] = None
    templateFile: TemplateFileContents


class CreateEnvironmentAccountConnectionInput(BaseModel):
    clientToken: Optional[ClientToken] = None
    codebuildRoleArn: Optional[RoleArn] = None
    componentRoleArn: Optional[RoleArn] = None
    environmentName: ResourceName
    managementAccountId: AwsAccountId
    roleArn: Optional[RoleArn] = None
    tags: Optional[TagList] = None


class CreateEnvironmentAccountConnectionOutput(BaseModel):
    environmentAccountConnection: EnvironmentAccountConnection


class CreateEnvironmentInput(BaseModel):
    codebuildRoleArn: Optional[RoleArn] = None
    componentRoleArn: Optional[RoleArn] = None
    description: Optional[Description] = None
    environmentAccountConnectionId: Optional[EnvironmentAccountConnectionId] = None
    name: ResourceName
    protonServiceRoleArn: Optional[Arn] = None
    provisioningRepository: Optional[RepositoryBranchInput] = None
    spec: SpecContents
    tags: Optional[TagList] = None
    templateMajorVersion: TemplateVersionPart
    templateMinorVersion: Optional[TemplateVersionPart] = None
    templateName: ResourceName


class CreateEnvironmentTemplateInput(BaseModel):
    description: Optional[Description] = None
    displayName: Optional[DisplayName] = None
    encryptionKey: Optional[Arn] = None
    name: ResourceName
    provisioning: Optional[Provisioning] = None
    tags: Optional[TagList] = None


class CreateEnvironmentTemplateOutput(BaseModel):
    environmentTemplate: EnvironmentTemplate


class CreateEnvironmentTemplateVersionInput(BaseModel):
    clientToken: Optional[ClientToken] = None
    description: Optional[Description] = None
    majorVersion: Optional[TemplateVersionPart] = None
    source: TemplateVersionSourceInput
    tags: Optional[TagList] = None
    templateName: ResourceName


class CreateEnvironmentTemplateVersionOutput(BaseModel):
    environmentTemplateVersion: EnvironmentTemplateVersion


class CreateRepositoryInput(BaseModel):
    connectionArn: Arn
    encryptionKey: Optional[Arn] = None
    name: RepositoryName
    provider: RepositoryProvider
    tags: Optional[TagList] = None


class CreateRepositoryOutput(BaseModel):
    repository: Repository


class CreateServiceInput(BaseModel):
    branchName: Optional[GitBranchName] = None
    description: Optional[Description] = None
    name: ResourceName
    repositoryConnectionArn: Optional[Arn] = None
    repositoryId: Optional[RepositoryId] = None
    spec: SpecContents
    tags: Optional[TagList] = None
    templateMajorVersion: TemplateVersionPart
    templateMinorVersion: Optional[TemplateVersionPart] = None
    templateName: ResourceName


class CreateServiceInstanceInput(BaseModel):
    clientToken: Optional[ClientToken] = None
    name: ResourceName
    serviceName: ResourceName
    spec: SpecContents
    tags: Optional[TagList] = None
    templateMajorVersion: Optional[TemplateVersionPart] = None
    templateMinorVersion: Optional[TemplateVersionPart] = None


class CreateServiceInstanceOutput(BaseModel):
    serviceInstance: ServiceInstance


class CreateServiceTemplateInput(BaseModel):
    description: Optional[Description] = None
    displayName: Optional[DisplayName] = None
    encryptionKey: Optional[Arn] = None
    name: ResourceName
    pipelineProvisioning: Optional[Provisioning] = None
    tags: Optional[TagList] = None


class CreateServiceTemplateOutput(BaseModel):
    serviceTemplate: ServiceTemplate


class CreateServiceTemplateVersionInput(BaseModel):
    clientToken: Optional[ClientToken] = None
    compatibleEnvironmentTemplates: CompatibleEnvironmentTemplateInputList
    description: Optional[Description] = None
    majorVersion: Optional[TemplateVersionPart] = None
    source: TemplateVersionSourceInput
    supportedComponentSources: Optional[
        ServiceTemplateSupportedComponentSourceInputList
    ] = None
    tags: Optional[TagList] = None
    templateName: ResourceName


class CreateServiceTemplateVersionOutput(BaseModel):
    serviceTemplateVersion: ServiceTemplateVersion


class CreateTemplateSyncConfigOutput(BaseModel):
    templateSyncConfig: Optional[TemplateSyncConfig] = None


class DeleteEnvironmentAccountConnectionOutput(BaseModel):
    environmentAccountConnection: Optional[EnvironmentAccountConnection] = None


class DeleteEnvironmentTemplateOutput(BaseModel):
    environmentTemplate: Optional[EnvironmentTemplate] = None


class DeleteEnvironmentTemplateVersionOutput(BaseModel):
    environmentTemplateVersion: Optional[EnvironmentTemplateVersion] = None


class DeleteRepositoryOutput(BaseModel):
    repository: Optional[Repository] = None


class DeleteServiceTemplateOutput(BaseModel):
    serviceTemplate: Optional[ServiceTemplate] = None


class DeleteServiceTemplateVersionOutput(BaseModel):
    serviceTemplateVersion: Optional[ServiceTemplateVersion] = None


class DeleteTemplateSyncConfigOutput(BaseModel):
    templateSyncConfig: Optional[TemplateSyncConfig] = None


class Environment(BaseModel):
    arn: EnvironmentArn
    codebuildRoleArn: Optional[RoleArn] = None
    componentRoleArn: Optional[RoleArn] = None
    createdAt: Timestamp
    deploymentStatus: DeploymentStatus
    deploymentStatusMessage: Optional[StatusMessage] = None
    description: Optional[Description] = None
    environmentAccountConnectionId: Optional[EnvironmentAccountConnectionId] = None
    environmentAccountId: Optional[AwsAccountId] = None
    lastDeploymentAttemptedAt: Timestamp
    lastDeploymentSucceededAt: Timestamp
    name: ResourceName
    protonServiceRoleArn: Optional[Arn] = None
    provisioning: Optional[Provisioning] = None
    provisioningRepository: Optional[RepositoryBranch] = None
    spec: Optional[SpecContents] = None
    templateMajorVersion: TemplateVersionPart
    templateMinorVersion: TemplateVersionPart
    templateName: ResourceName


class GetAccountSettingsOutput(BaseModel):
    accountSettings: Optional[AccountSettings] = None


class GetEnvironmentOutput(BaseModel):
    environment: Environment


class GetRepositoryOutput(BaseModel):
    repository: Repository


class GetServiceInstanceOutput(BaseModel):
    serviceInstance: ServiceInstance


class GetServiceTemplateOutput(BaseModel):
    serviceTemplate: ServiceTemplate


class GetServiceTemplateVersionOutput(BaseModel):
    serviceTemplateVersion: ServiceTemplateVersion


class GetTemplateSyncConfigOutput(BaseModel):
    templateSyncConfig: Optional[TemplateSyncConfig] = None


class LatestSyncBlockers(RootModel[List[SyncBlocker]]):
    root: List[SyncBlocker]


class ListComponentOutputsOutput(BaseModel):
    nextToken: Optional[EmptyNextToken] = None
    outputs: OutputsList


class ListComponentProvisionedResourcesOutput(BaseModel):
    nextToken: Optional[EmptyNextToken] = None
    provisionedResources: ProvisionedResourceList


class ListEnvironmentOutputsOutput(BaseModel):
    nextToken: Optional[EmptyNextToken] = None
    outputs: OutputsList


class ListEnvironmentProvisionedResourcesOutput(BaseModel):
    nextToken: Optional[EmptyNextToken] = None
    provisionedResources: ProvisionedResourceList


class ListRepositorySyncDefinitionsOutput(BaseModel):
    nextToken: Optional[EmptyNextToken] = None
    syncDefinitions: RepositorySyncDefinitionList


class ListServiceInstanceOutputsOutput(BaseModel):
    nextToken: Optional[EmptyNextToken] = None
    outputs: OutputsList


class ListServiceInstanceProvisionedResourcesOutput(BaseModel):
    nextToken: Optional[EmptyNextToken] = None
    provisionedResources: ProvisionedResourceList


class ListServiceInstancesOutput(BaseModel):
    nextToken: Optional[NextToken] = None
    serviceInstances: ServiceInstanceSummaryList


class ListServicePipelineOutputsOutput(BaseModel):
    nextToken: Optional[EmptyNextToken] = None
    outputs: OutputsList


class ListServicePipelineProvisionedResourcesOutput(BaseModel):
    nextToken: Optional[EmptyNextToken] = None
    provisionedResources: ProvisionedResourceList


class ListServiceTemplateVersionsOutput(BaseModel):
    nextToken: Optional[NextToken] = None
    templateVersions: ServiceTemplateVersionSummaryList


class ListServiceTemplatesOutput(BaseModel):
    nextToken: Optional[NextToken] = None
    templates: ServiceTemplateSummaryList


class ListServicesOutput(BaseModel):
    nextToken: Optional[NextToken] = None
    services: ServiceSummaryList


class ListTagsForResourceOutput(BaseModel):
    nextToken: Optional[String] = None
    tags: TagList


class NotifyResourceDeploymentStatusChangeInputOutputsList(RootModel[List[Output]]):
    root: List[Output] = Field(..., max_length=50, min_length=0)


class RepositorySyncAttempt(BaseModel):
    events: RepositorySyncEvents
    startedAt: Timestamp
    status: RepositorySyncStatus


class ResourceSyncAttempt(BaseModel):
    events: ResourceSyncEvents
    initialRevision: Revision
    startedAt: Timestamp
    status: ResourceSyncStatus
    target: String
    targetRevision: Revision


class Service(BaseModel):
    arn: ServiceArn
    branchName: Optional[GitBranchName] = None
    createdAt: Timestamp
    description: Optional[Description] = None
    lastModifiedAt: Timestamp
    name: ResourceName
    pipeline: Optional[ServicePipeline] = None
    repositoryConnectionArn: Optional[Arn] = None
    repositoryId: Optional[RepositoryId] = None
    spec: SpecContents
    status: ServiceStatus
    statusMessage: Optional[StatusMessage] = None
    templateName: ResourceName


class ServiceSyncBlockerSummary(BaseModel):
    latestBlockers: Optional[LatestSyncBlockers] = None
    serviceInstanceName: Optional[String] = None
    serviceName: String


class UpdateAccountSettingsOutput(BaseModel):
    accountSettings: AccountSettings


class UpdateEnvironmentOutput(BaseModel):
    environment: Environment


class UpdateServiceOutput(BaseModel):
    service: Service


class CancelEnvironmentDeploymentOutput(BaseModel):
    environment: Environment


class CreateEnvironmentOutput(BaseModel):
    environment: Environment


class CreateServiceOutput(BaseModel):
    service: Service


class DeleteEnvironmentOutput(BaseModel):
    environment: Optional[Environment] = None


class DeleteServiceOutput(BaseModel):
    service: Optional[Service] = None


class GetRepositorySyncStatusOutput(BaseModel):
    latestSync: Optional[RepositorySyncAttempt] = None


class GetServiceInstanceSyncStatusOutput(BaseModel):
    desiredState: Optional[Revision] = None
    latestSuccessfulSync: Optional[ResourceSyncAttempt] = None
    latestSync: Optional[ResourceSyncAttempt] = None


class GetServiceOutput(BaseModel):
    service: Optional[Service] = None


class GetServiceSyncBlockerSummaryOutput(BaseModel):
    serviceSyncBlockerSummary: Optional[ServiceSyncBlockerSummary] = None


class GetTemplateSyncStatusOutput(BaseModel):
    desiredState: Optional[Revision] = None
    latestSuccessfulSync: Optional[ResourceSyncAttempt] = None
    latestSync: Optional[ResourceSyncAttempt] = None


class NotifyResourceDeploymentStatusChangeInput(BaseModel):
    deploymentId: Optional[DeploymentId] = None
    outputs: Optional[NotifyResourceDeploymentStatusChangeInputOutputsList] = None
    resourceArn: Arn
    status: Optional[ResourceDeploymentStatus] = None
    statusMessage: Optional[
        NotifyResourceDeploymentStatusChangeInputStatusMessageString
    ] = None
